### ISSUE TITLE
Mapeamento da pista

### ISSUE THREAD

**Issue by raphera** [Tamandutech/LineFollower_Braia_Code#23]
- [x] Coletar marcações.
- [x] Testar coleta de marcações.
- [x] Descrever fluxo de mapeamento da pista e dados envolvidos.

**Comment by Matheus-de-Sousa** [comment]
O mapeamento está finalizado, falta agora implemntá-lo via wifi com espnow e discutir alguns detalhes de funcionamento do robô

**Comment by Matheus-de-Sousa** [comment]
O mapeamento está finalizado, falta agora implemntá-lo via wifi com espnow e discutir alguns detalhes de funcionamento do robô
