### ISSUE TITLE
Estudo do código atual

### ISSUE THREAD

**Issue by raphera** [Tamandutech/LineFollower_Braia_Code#35]
<h2>Gabriel Barreto</h2>

- [x] Instalar dependências
  - [x] [Git](https://git-scm.com/)
  - [x] [VSCode](https://code.visualstudio.com/)
  - [x] [PlatformIO](https://platformio.org/install/ide?install=vscode)
- [x] Clonar o repositório
- [x] Compilar o código pela primeira vez (só clicar em build e ver se da sucesso)
- [x] Estudar inicialização do robô, o que ele faz assim que liga?

<h2>Giovanni Rodrigues</h2>

- [x] Instalar dependências
  - [x] [Git](https://git-scm.com/)
  - [x] [VSCode](https://code.visualstudio.com/)
  - [x] [PlatformIO](https://platformio.org/install/ide?install=vscode)
- [x] Clonar o repositório
- [x] Compilar o código pela primeira vez (só clicar em build e ver se da sucesso)
- [x] Estudar inicialização do robô, o que ele faz assim que liga?

<h2>Pedro Marcondes</h2>

- [x] Instalar dependências
  - [x] [Git](https://git-scm.com/)
  - [x] [VSCode](https://code.visualstudio.com/)
  - [x] [PlatformIO](https://platformio.org/install/ide?install=vscode)
- [x] Clonar o repositório
- [x] Compilar o código pela primeira vez (só clicar em build e ver se da sucesso)
- [x] Estudar inicialização do robô, o que ele faz assim que liga?

**Comment by Pedromone** [comment]
De primeira estava dando alguns erros de falta de extensões e necessitando assim instalando as mesmas

De segunda, tive alguns problemas de lentidão na leitura dos códigos, e erros nas instalações, precisando assim, um quick start no platformIO

De terceira e gloriosa vez, eu e o matheus ficamos debrulhando o motivo da platformIO não conseguir encontrar seu proprio arquivo, por conta disso, fizemos algumas formatações tanta nas extensões quanto no proprio codigo. Por fim, deu certo.
Com a build sendo rodada e "inicializando/processando" todas as instancias.

Aqui vai algumas imagens da saga 
![image](https://user-images.githubusercontent.com/58983667/174125532-3e5f2afd-1c1d-4d67-865b-9367895761c8.png)
![image](https://user-images.githubusercontent.com/58983667/174125569-406aefc8-f1b8-4497-8b5d-6e07172605d4.png)
![image](https://user-images.githubusercontent.com/58983667/174125668-f9e51132-cc33-4e85-9910-0efe085fa6f9.png)

Matheus imagens abaixo
![image](https://user-images.githubusercontent.com/58983667/174125598-71227aaa-464a-49ba-90b3-fce5a1905b4e.png)
![image](https://user-images.githubusercontent.com/58983667/174125639-0cd81988-4604-4703-acf7-cd8ba9506288.png)

**Comment by Pedromone** [comment]
PROCESSO DE BUILDAR TUDO DE UMA VEZ
![image](https://user-images.githubusercontent.com/58983667/174126829-75791582-e949-45a3-bece-de8b85766ee0.png)

**Comment by Pedromone** [comment]
:)
![image](https://user-images.githubusercontent.com/58983667/174128971-d1fb766d-3ff8-4e1d-b1a5-d9d7377cad8c.png)

**Comment by giovannirdias** [comment]
**O que o robô faz assim que liga?**

No primeiro momento foi isso que entendi ao ler a main_robot.cpp e os arquivos de execução e cabeçalho nos diretórios de serviços e dados. Se identificarem algo de errado ou que tiver que complementar algum ponto sobre a inicialização, avise-me se puder.

Inicialmente cria-se as instâncias referentes aos serviços e os dados dos robôs, com a utilização do serviço LEDsService para indicar a partir dos comandos de cores qual é operação está sendo executada no main_robot.cpp (ESP_LOGD &#8594;  Método de registro).  

```
ESP_LOGD("MAIN", "LED Vermelho");
ledsService->queueCommand(command);
mappingService = MappingService::getInstance("MappingService", 8192, 18);
.........................................................................

ESP_LOGD("MAIN", "LED Laranja");
command.color = LED_COLOR_ORANGE;
ledsService->queueCommand(command);
sensorsService->Start();
```

Após isso, o robô terá seu status colocado no modo parado, aguardando o pressionamento do botão novamente (xQueueReceive(gpio_evt_queue, &num, portMAX_DELAY)) para modificar esse status para linha ou curva, executando a função de mapeamento da pista para identificar as características e os valores dos parâmetros referentes ao mapeamento, PID (velocidade rotacional e translacional) e velocidade do motores.
