### ISSUE TITLE
Utilizar o botão de boot para deletar o mapeamento

### ISSUE THREAD

**Issue by Matheus-de-Sousa** [Tamandutech/LineFollower_Braia_Code#48]
Ao iniciar o robô precisa que o botão de boot seja pressionado para começar a andar, e ele decide a sua função com base nos dados de mapeamento gravados na flash, dessa forma será útil se ao segurar o botão de boot o mapeamento seja deletado, facilitando o controle da função do robô

**Comment by Matheus-de-Sousa** [comment]
Arquivo que deve ser alterado [CarStatusService](https://github.com/Tamandutech/LineFollower_Braia_Code/blob/develop/modules/robot/services/CarStatusService/src/CarStatusService.cpp)

**Comment by Pedromone** [comment]
Completado :)
